sudo: required

services:
  - docker

language: go
go:
  - "1.15"

env:
  global:
    - PATH=/home/travis/gopath/bin:$PATH
    - COMMIT=${TRAVIS_COMMIT::8}
    # - REPO=kbudde/rabbitmq-exporter
    - GO111MODULE=on
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/aktau/github-release
  - git checkout -B ${TRAVIS_BRANCH}


install:
  - go mod download

script:
  - go test -tags integration -covermode=count -coverprofile=coverage.out ./
  
#Build dist releases 
  - if [ -n "$TRAVIS_TAG" ]; then make tarballs && promu release .tarballs ; fi
  
#Submit coverage
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
